# Generated by Django 4.2.6 on 2023-11-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(choices=[('Banteay Meanchey', 'Banteay Meanchey'), ('Battambang', 'Battambang'), ('Kampong Cham', 'Kampong Cham'), ('Kampong Chhnang', 'Kampong Chhnang'), ('Kampong Speu', 'Kampong Speu'), ('Kampong Thom', 'Kampong Thom'), ('Kampot', 'Kampot'), ('Kandal', 'Kandal'), ('Kep', 'Kep'), ('Koh Kong', 'Koh Kong'), ('Kratié', 'Kratié'), ('Mondulkiri', 'Mondulkiri'), ('Oddar Meanchey', 'Oddar Meanchey'), ('Pailin', 'Pailin'), ('Phnom Penh', 'Phnom Penh'), ('Preah Sihanouk', 'Preah Sihanouk'), ('Preah Vihear', 'Preah Vihear'), ('Pursat', 'Pursat'), ('Ratanakiri', 'Ratanakiri'), ('Siem Reap', 'Siem Reap'), ('Prey Veng', 'Prey Veng'), ('Stung Treng', 'Stung Treng'), ('Svay Rieng', 'Svay Rieng'), ('Takeo', 'Takeo'), ('Tbong Khmum', 'Tbong Khmum')], max_length=500)),
                ('contact', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HouseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParkingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrashPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNo', models.CharField(max_length=200)),
                ('RoomFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(max_length=200)),
                ('HouseOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.houseowner')),
            ],
        ),
    ]
