# Generated by Django 4.2.6 on 2023-11-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='ParkingQty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
