# Generated by Django 4.2.6 on 2023-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_parking_parkingqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
