# Generated by Django 4.2.6 on 2023-11-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_parking_parkingqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.parking'),
        ),
    ]
