# Generated by Django 4.2.6 on 2023-11-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_checkin_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='parking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.parking'),
        ),
    ]
