# Generated by Django 4.2.6 on 2023-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_checkin_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='trash',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='parking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='parking',
        ),
    ]
