# Generated by Django 4.2.6 on 2023-11-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_checkin_trash_alter_checkin_parking_delete_parking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
