# Generated by Django 4.2.6 on 2023-11-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='ClientName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='dashboard.room'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='ClientName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='dashboard.room'),
        ),
    ]
