# Generated by Django 4.2.6 on 2023-11-27 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_checkin_clientname_alter_checkin_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 27)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 27)),
        ),
    ]
