# Generated by Django 4.2.6 on 2023-11-27 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_checkin_date_alter_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='ClientName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
