# Generated by Django 4.2.6 on 2023-11-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_checkin_clientname_alter_checkin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='ClientName',
        ),
        migrations.AddField(
            model_name='checkin',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.client'),
        ),
    ]
