# Generated by Django 4.2.6 on 2023-11-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_checkin_client_checkin_client_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='dashboard.room')),
            ],
        ),
    ]
