# Generated by Django 4.2.6 on 2023-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available/ទំនេរ', 'Available/ទំនេរ'), ('In-use/កំពុង\u200bប្រើ', 'In-use/កំពុង\u200bប្រើ')], default='Available/ទំនេរ', max_length=20),
        ),
    ]
