# Generated by Django 4.2.6 on 2023-11-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRentalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.parking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room')),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.trash')),
                ('utilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.utilities')),
            ],
        ),
    ]
