# Generated by Django 4.2.6 on 2023-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_monthlyrentalfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='other_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
