# Generated by Django 4.2.6 on 2023-11-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_utilities_other_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='previous_water',
            field=models.IntegerField(),
        ),
    ]
