# Generated by Django 4.2.6 on 2023-11-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_utilities_previous_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrentalfee',
            name='client',
        ),
        migrations.RemoveField(
            model_name='monthlyrentalfee',
            name='room',
        ),
        migrations.AddField(
            model_name='monthlyrentalfee',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.checkin'),
        ),
        migrations.AlterField(
            model_name='monthlyrentalfee',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
