# Generated by Django 4.2.6 on 2023-11-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_monthlyrentalfee_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='previous_water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
