# Generated by Django 4.2.6 on 2023-11-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_monthlyrentalfee_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_usage_history', to='dashboard.utilities')),
            ],
        ),
    ]
