# Generated by Django 4.2.5 on 2023-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_waterusagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='current_water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
