# Generated by Django 4.2.5 on 2023-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_utilities_current_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrentalfee',
            name='water_fee',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
