# Generated by Django 4.2.5 on 2023-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_monthlyrentalfee_water_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrentalfee',
            name='water_rate',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
