# Generated by Django 4.2.6 on 2023-11-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_room_check_in_alter_checkin_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in',
        ),
    ]
