# Generated by Django 4.2.7 on 2023-11-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_room_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='dashboard.room'),
        ),
    ]
