# Generated by Django 4.2.7 on 2023-12-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_checkin_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.client'),
        ),
    ]
