# Generated by Django 4.2.7 on 2023-12-02 10:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='previous_water',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='waterusagehistory',
            name='previous_water',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
