# Generated by Django 4.2.7 on 2023-12-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_utilities_previous_water_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrentalfee',
            name='checkin',
        ),
    ]
