# Generated by Django 4.2.7 on 2023-12-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_remove_monthlyrentalfee_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('monthly_rental_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.monthlyrentalfee')),
            ],
        ),
    ]
