# Generated by Django 4.2.7 on 2023-12-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrentalfee',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='monthlyrentalfee',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='monthlyrentalfee',
            name='utilities',
        ),
        migrations.RemoveField(
            model_name='utilities',
            name='room',
        ),
        migrations.RemoveField(
            model_name='waterusagehistory',
            name='utilities',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='MonthlyRentalFee',
        ),
        migrations.DeleteModel(
            name='utilities',
        ),
        migrations.DeleteModel(
            name='WaterUsageHistory',
        ),
    ]
