# Generated by Django 4.2.7 on 2023-12-03 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_monthlyrentalfee_parking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_quantity', models.PositiveIntegerField(default=0)),
                ('previous_water_quantity', models.PositiveIntegerField(default=0)),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='dashboard.room')),
                ('water_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.waterrate')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRentalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('water_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trash_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('park_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='dashboard.room')),
            ],
        ),
    ]
