# Generated by Django 4.2.7 on 2023-12-03 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_waterrate_utilities_monthlyrentalfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilities',
            name='previous_date',
        ),
        migrations.AddField(
            model_name='utilities',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
