# Generated by Django 4.2.7 on 2023-12-07 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_client_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrentalfee',
            name='previous_water',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('house_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.houseowner')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_usage', to='dashboard.room')),
            ],
        ),
    ]
