# Generated by Django 4.2.7 on 2023-12-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_monthlyrentalfee_previous_water_waterusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrentalfee',
            name='previous_water',
        ),
    ]
