# Generated by Django 4.2.7 on 2023-12-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_remove_monthlyrentalfee_previous_water'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilities',
            old_name='water_quantity',
            new_name='previous_water',
        ),
    ]
