# Generated by Django 4.2.7 on 2023-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_rename_water_quantity_utilities_previous_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='current_water',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
