# Generated by Django 4.2.7 on 2023-12-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_monthlyrentalfee_previous_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='trash',
        ),
    ]
