# Generated by Django 4.2.7 on 2023-12-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_remove_checkin_parking_remove_checkin_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrentalfee',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
